import type { Product } from "@/types";
import shemoProducts from "./shemo-products.json";

/**
 * Catalog-imported products (machine-managed).
 *
 * The JSON store is generated by `scripts/import-shemo.mjs` and merged into the
 * main catalog by `src/data/products.ts`. Do not hand-edit the JSON — re-run the
 * importer instead (it is idempotent and keyed by product code).
 *
 * The cast is required because JSON literal types widen (e.g. `visual.form`
 * becomes `string`); the importer guarantees the values conform to `Product`.
 */
export const importedProducts: Product[] = shemoProducts as unknown as Product[];
