#!/usr/bin/env node
/**
 * Builds the product-image review page from a fetch report.
 * ---------------------------------------------------------
 * One self-contained HTML file: every thumbnail travels inside it, so the page
 * works from a link, from disk, and on a phone, with no server and no external
 * image host.
 *
 * The photos are shown the way the website shows product photos — contained,
 * never cropped, on a light studio panel (see src/components/ui/ProductMedia.tsx)
 * — so judging them here means judging how they will actually look.
 *
 * Thumbnails are generated by make-thumbs.py, which this script runs for you
 * when Pillow is available; without it the originals are embedded instead and
 * the page just gets heavier.
 *
 * Usage:
 *   node scripts/product-images/build-preview.mjs                    # batch1
 *   node scripts/product-images/build-preview.mjs --label batch2
 *   node scripts/product-images/build-preview.mjs --out /tmp/vorschau.html
 */

import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SCRIPTS_DIR = path.resolve(__dirname, "..");
const ROOT = path.resolve(SCRIPTS_DIR, "..");
const REPORT_DIR = path.join(SCRIPTS_DIR, "reports");
const THUMB_DIR = path.join(ROOT, ".image-cache", "thumbs");

const MIME = { ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".png": "image/png", ".webp": "image/webp" };

function readArgs(argv) {
  const flag = (name, fallback) => {
    const i = argv.indexOf(`--${name}`);
    return i === -1 || i + 1 >= argv.length ? fallback : argv[i + 1];
  };
  const label = flag("label", "batch1");
  return {
    label,
    report: flag("report", path.join(REPORT_DIR, `product-images-${label}.json`)),
    out: flag("out", path.join(ROOT, ".image-cache", `vorschau-${label}.html`)),
    skipThumbs: argv.includes("--skip-thumbs"),
  };
}

const escapeHtml = (value) =>
  String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const formatPrice = (value) =>
  typeof value === "number" ? `${value.toFixed(2).replace(".", ",")} €` : "—";

/** Group the barcode the way it is printed on the pack: 4 + 6 + 3 for EAN-13. */
function formatBarcode(code) {
  if (code?.length === 13) return `${code.slice(0, 4)} ${code.slice(4, 10)} ${code.slice(10)}`;
  if (code?.length === 8) return `${code.slice(0, 4)} ${code.slice(4)}`;
  return code || "—";
}

const thumbsBuilt = () => fs.existsSync(THUMB_DIR) && fs.readdirSync(THUMB_DIR).length > 0;

/**
 * Returns the image as a data URI, or `{ damaged: true }` when the file is
 * there but unreadable — a truncated download that would otherwise render as a
 * broken image and be mistaken for a missing photo.
 */
function embedImage(product) {
  if (!product.file) return null;
  const original = path.join(ROOT, product.file);
  const thumb = path.join(THUMB_DIR, `${path.basename(product.file, path.extname(product.file))}.jpg`);
  if (fs.existsSync(thumb)) {
    return `data:image/jpeg;base64,${fs.readFileSync(thumb).toString("base64")}`;
  }
  // No thumbnail although thumbnails were built means Pillow rejected the file.
  if (thumbsBuilt()) return { damaged: true };
  if (!fs.existsSync(original)) return null;
  const mime = MIME[path.extname(original).toLowerCase()];
  if (!mime) return null;
  return `data:${mime};base64,${fs.readFileSync(original).toString("base64")}`;
}

function card(product, index) {
  const embedded = embedImage(product);
  const damaged = Boolean(embedded && embedded.damaged);
  const src = damaged ? null : embedded;
  const found = Boolean(src);
  const search = [product.name, product.brand, product.barcode, product.code, product.confidence]
    .join(" ")
    .toLowerCase();

  const media = found
    ? `<img class="shot" src="${src}" alt="${escapeHtml(product.name)}" loading="lazy" decoding="async">`
    : `<div class="shot-missing"><span>${damaged ? "fotografia e dëmtuar" : "nuk u gjet foto"}</span></div>`;

  // Only the uncertain ones get a badge. Flagging all fifty as "high" would
  // decorate the grid without telling the reviewer where to look.
  const flag =
    product.confidence && product.confidence !== "E lartë"
      ? `<p class="flag">Besueshmëria: ${escapeHtml(product.confidence)}</p>`
      : "";
  const warnings = (product.warnings ?? []).length
    ? `<p class="flag warn">${product.warnings.map(escapeHtml).join(" · ")}</p>`
    : "";

  const source = product.sourceUrl
    ? `<a class="source" href="${escapeHtml(product.sourceUrl)}" target="_blank" rel="noopener noreferrer">${escapeHtml(product.source)} · ${escapeHtml(product.licence ?? "")}</a>`
    : `<span class="source muted">${escapeHtml(product.status)}</span>`;

  return `
      <article class="card" data-code="${escapeHtml(product.code)}" data-brand="${escapeHtml(product.brand)}"
               data-found="${found}" data-search="${escapeHtml(search)}">
        <div class="rank">${index + 1}</div>
        <div class="panel">${media}</div>
        <div class="meta">
          <p class="name">${escapeHtml(product.name)}</p>
          <p class="brand">${escapeHtml(product.brand || "pa markë")}</p>
          ${flag}${warnings}
          <dl class="facts">
            <div><dt>Barkodi</dt><dd class="mono">${formatBarcode(product.barcode)}</dd></div>
            <div><dt>Kodi</dt><dd class="mono">${escapeHtml(product.code)}</dd></div>
            <div><dt>Çmimi</dt><dd class="mono">${formatPrice(product.price)}</dd></div>
          </dl>
          ${source}
        </div>
        <div class="verdict" role="group" aria-label="Vlerësimi për ${escapeHtml(product.name)}">
          <button type="button" data-mark="ok" aria-pressed="false">Mirë</button>
          <button type="button" data-mark="unsure" aria-pressed="false">Dyshim</button>
          <button type="button" data-mark="wrong" aria-pressed="false">Gabim</button>
        </div>
      </article>`;
}

function page(report, cards, brands) {
  const { totals, label } = report;
  const generated = new Date(report.generatedAt).toLocaleDateString("sq-AL", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });

  // The label is what separates one review batch from the next, so it belongs
  // in the title too: published side by side, two batches otherwise show up
  // under one indistinguishable name.
  const prettyLabel = label
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());

  return `<title>Fotot e Produkteve — ${escapeHtml(prettyLabel)}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap">
<style>
  :root {
    --ground: #F7FAF8;
    --raised: #FFFFFF;
    --ink: #0F172A;
    --ink-muted: #64748B;
    --line: #DCE7E1;
    --forest: #0A5C44;
    --emerald: #0F7A57;
    --lime: #B7E532;
    --ok: #0F7A57;
    --ok-soft: #EAF8F0;
    --unsure: #8A6D1F;
    --unsure-soft: #FFF6D8;
    --wrong: #C2427A;
    --wrong-soft: #FBE7F0;
    --shadow: 0 1px 2px rgba(7, 59, 45, .06), 0 8px 24px rgba(7, 59, 45, .07);
    --radius: 18px;
    --sans: "Inter", system-ui, -apple-system, "Segoe UI", sans-serif;
    --mono: "IBM Plex Mono", ui-monospace, "SFMono-Regular", monospace;
  }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      --ground: #04241C;
      --raised: #073B2D;
      --ink: #EAF4EF;
      --ink-muted: #9FCFB9;
      --line: #0C4634;
      --forest: #CDEE63;
      --emerald: #66B294;
      --ok: #9FCFB9;
      --ok-soft: #0C6349;
      --unsure: #FFF6D8;
      --unsure-soft: #6B5613;
      --wrong: #F7D8E5;
      --wrong-soft: #8A2E58;
      --shadow: 0 1px 2px rgba(0, 0, 0, .3), 0 8px 24px rgba(0, 0, 0, .28);
    }
  }
  :root[data-theme="dark"] {
    --ground: #04241C;
    --raised: #073B2D;
    --ink: #EAF4EF;
    --ink-muted: #9FCFB9;
    --line: #0C4634;
    --forest: #CDEE63;
    --emerald: #66B294;
    --ok: #9FCFB9;
    --ok-soft: #0C6349;
    --unsure: #FFF6D8;
    --unsure-soft: #6B5613;
    --wrong: #F7D8E5;
    --wrong-soft: #8A2E58;
    --shadow: 0 1px 2px rgba(0, 0, 0, .3), 0 8px 24px rgba(0, 0, 0, .28);
  }

  * { box-sizing: border-box; }
  body {
    margin: 0;
    background: var(--ground);
    color: var(--ink);
    font-family: var(--sans);
    font-size: 15px;
    line-height: 1.5;
    -webkit-font-smoothing: antialiased;
  }
  .wrap { max-width: 1280px; margin: 0 auto; padding: 0 20px 96px; }

  header.masthead { padding: 40px 0 24px; display: flex; flex-direction: column; gap: 10px; }
  .eyebrow {
    font-size: 12px; font-weight: 600; letter-spacing: .12em; text-transform: uppercase;
    color: var(--emerald);
  }
  h1 { margin: 0; font-size: clamp(26px, 4vw, 36px); font-weight: 700; letter-spacing: -.02em; text-wrap: balance; }
  .lede { margin: 0; max-width: 62ch; color: var(--ink-muted); }

  .tally { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 6px; }
  .tally span {
    display: inline-flex; align-items: baseline; gap: 6px;
    padding: 6px 12px; border-radius: 999px; border: 1px solid var(--line);
    background: var(--raised); font-size: 13px; color: var(--ink-muted);
  }
  .tally b { color: var(--ink); font-family: var(--mono); font-variant-numeric: tabular-nums; }

  .toolbar {
    position: sticky; top: 0; z-index: 5;
    display: flex; flex-wrap: wrap; gap: 10px; align-items: center;
    padding: 14px 0; margin-bottom: 20px;
    background: color-mix(in srgb, var(--ground) 92%, transparent);
    backdrop-filter: blur(8px);
    border-bottom: 1px solid var(--line);
  }
  .search {
    flex: 1 1 220px; min-width: 180px;
    padding: 9px 14px; border-radius: 999px;
    border: 1px solid var(--line); background: var(--raised); color: var(--ink);
    font: inherit;
  }
  .search::placeholder { color: var(--ink-muted); }
  .chips { display: flex; flex-wrap: wrap; gap: 6px; }
  .chip {
    padding: 6px 12px; border-radius: 999px; border: 1px solid var(--line);
    background: var(--raised); color: var(--ink-muted);
    font: inherit; font-size: 13px; cursor: pointer;
  }
  .chip[aria-pressed="true"] {
    background: var(--forest); border-color: var(--forest);
    color: var(--raised); font-weight: 600;
  }
  :root[data-theme="dark"] .chip[aria-pressed="true"],
  :root:not([data-theme="light"]) .chip[aria-pressed="true"] { color: #04241C; }
  @media (prefers-color-scheme: light) {
    :root:not([data-theme="dark"]) .chip[aria-pressed="true"] { color: #FFFFFF; }
  }

  .grid {
    display: grid; gap: 18px;
    grid-template-columns: repeat(auto-fill, minmax(226px, 1fr));
  }
  .card {
    position: relative; display: flex; flex-direction: column;
    background: var(--raised); border: 1px solid var(--line);
    border-radius: var(--radius); box-shadow: var(--shadow); overflow: hidden;
  }
  .card[hidden] { display: none; }
  .rank {
    position: absolute; top: 10px; left: 10px; z-index: 2;
    min-width: 26px; height: 22px; padding: 0 7px;
    display: grid; place-items: center;
    border-radius: 999px; background: rgba(255, 255, 255, .92);
    border: 1px solid rgba(10, 92, 68, .18);
    color: #0A5C44; font-family: var(--mono); font-size: 11px; font-variant-numeric: tabular-nums;
  }
  /* Packshots are photographed on white; the panel stays light in both themes,
     matching how the site presents product photos. */
  .panel {
    flex: none; /* equal-height cards must not stretch the photo panel */
    aspect-ratio: 4 / 5;
    background: linear-gradient(180deg, #FFFFFF 0%, #F4F7F5 100%);
    display: grid; place-items: center; overflow: hidden;
    border-bottom: 1px solid var(--line);
  }
  /* min-height:0 keeps a tall packshot from stretching the panel past its
     aspect ratio, which would break the row alignment. */
  .shot { width: 100%; height: 100%; min-width: 0; min-height: 0; object-fit: contain; padding: 9%; }
  .shot-missing {
    width: 100%; height: 100%; display: grid; place-items: center;
    color: #94A3B8; font-size: 13px;
    background-image: repeating-linear-gradient(45deg, transparent 0 10px, rgba(148,163,184,.10) 10px 20px);
  }

  .meta { display: flex; flex-direction: column; gap: 6px; padding: 12px 14px 4px; }
  .name { margin: 0; font-size: 13.5px; font-weight: 600; line-height: 1.35; }
  .brand { margin: 0; font-size: 12px; color: var(--emerald); font-weight: 600; letter-spacing: .02em; }
  .flag {
    margin: 0; align-self: flex-start;
    padding: 3px 9px; border-radius: 999px;
    background: var(--unsure-soft); color: var(--unsure);
    font-size: 11px; font-weight: 600;
  }
  .flag.warn { background: var(--wrong-soft); color: var(--wrong); font-weight: 500; }
  .facts { margin: 4px 0 0; display: grid; gap: 2px; font-size: 12px; }
  .facts div { display: flex; justify-content: space-between; gap: 10px; }
  .facts dt { color: var(--ink-muted); }
  .facts dd { margin: 0; }
  .mono { font-family: var(--mono); font-variant-numeric: tabular-nums; }
  .source {
    margin-top: 6px; font-size: 11.5px; color: var(--ink-muted);
    text-decoration: none; border-bottom: 1px dotted var(--line);
    align-self: flex-start; word-break: break-word;
  }
  .source:hover { color: var(--emerald); }
  .muted { border: 0; }

  .verdict { display: grid; grid-template-columns: repeat(3, 1fr); gap: 6px; padding: 10px 14px 14px; margin-top: auto; }
  .verdict button {
    padding: 7px 4px; border-radius: 10px; border: 1px solid var(--line);
    background: transparent; color: var(--ink-muted);
    font: inherit; font-size: 12px; cursor: pointer;
  }
  .verdict button:hover { border-color: var(--emerald); color: var(--ink); }
  .card[data-mark="ok"] .verdict button[data-mark="ok"] { background: var(--ok-soft); border-color: var(--ok); color: var(--ok); font-weight: 600; }
  .card[data-mark="unsure"] .verdict button[data-mark="unsure"] { background: var(--unsure-soft); border-color: var(--unsure); color: var(--unsure); font-weight: 600; }
  .card[data-mark="wrong"] .verdict button[data-mark="wrong"] { background: var(--wrong-soft); border-color: var(--wrong); color: var(--wrong); font-weight: 600; }
  .card[data-mark="ok"] { border-color: var(--ok); }
  .card[data-mark="wrong"] { border-color: var(--wrong); }
  .card[data-mark] .panel { opacity: .88; }

  .footbar {
    position: fixed; left: 0; right: 0; bottom: 0; z-index: 6;
    display: flex; flex-wrap: wrap; gap: 12px; align-items: center; justify-content: space-between;
    padding: 12px 20px;
    background: color-mix(in srgb, var(--raised) 94%, transparent);
    backdrop-filter: blur(8px); border-top: 1px solid var(--line);
  }
  .footbar p { margin: 0; font-size: 13px; color: var(--ink-muted); }
  .footbar b { color: var(--ink); font-family: var(--mono); font-variant-numeric: tabular-nums; }
  .copy {
    padding: 9px 18px; border-radius: 999px; border: 0;
    background: var(--forest); color: var(--raised);
    font: inherit; font-weight: 600; font-size: 13px; cursor: pointer;
  }
  :root[data-theme="dark"] .copy, :root:not([data-theme="light"]) .copy { color: #04241C; }
  @media (prefers-color-scheme: light) { :root:not([data-theme="dark"]) .copy { color: #FFFFFF; } }

  :focus-visible { outline: 2px solid var(--emerald); outline-offset: 2px; }
  .empty { padding: 60px 0; text-align: center; color: var(--ink-muted); }
  @media (prefers-reduced-motion: reduce) { * { transition: none !important; } }
</style>

<div class="wrap" lang="sq">
  <header class="masthead">
    <p class="eyebrow">Parapamje · ${escapeHtml(label)} · ${generated}</p>
    <h1>Fotot e produkteve për aprovim</h1>
    <p class="lede">Së pari produktet më të lehta: markë e njohur, barkod i verifikuar.
      Çdo foto shfaqet ashtu siç do të dukej në faqe. Shikoji një nga një dhe shëno
      vlerësimin — zgjedhjet ruhen në këtë shfletues.</p>
    <div class="tally">
      <span>Produkte <b>${totals.selected}</b></span>
      <span>me foto <b>${totals.found}</b></span>
      <span>pa rezultat <b>${totals.missing}</b></span>
      <span>Marka <b>${brands.length}</b></span>
    </div>
  </header>

  <div class="toolbar">
    <input class="search" type="search" id="q" placeholder="Kërko: emri, marka, barkodi…" aria-label="Kërko produkte">
    <div class="chips" id="statusChips">
      <button class="chip" type="button" data-status="all" aria-pressed="true">Të gjitha</button>
      <button class="chip" type="button" data-status="found" aria-pressed="false">Me foto</button>
      <button class="chip" type="button" data-status="missing" aria-pressed="false">Pa foto</button>
      <button class="chip" type="button" data-status="open" aria-pressed="false">Pa vlerësim</button>
    </div>
    <div class="chips" id="brandChips">
      ${brands.map((b) => `<button class="chip" type="button" data-brand="${escapeHtml(b)}" aria-pressed="false">${escapeHtml(b)}</button>`).join("\n      ")}
    </div>
  </div>

  <div class="grid" id="grid">${cards}
  </div>
  <p class="empty" id="empty" hidden>Asnjë produkt për këtë zgjedhje.</p>
</div>

<div class="footbar">
  <p><b id="doneCount">0</b> nga <b>${totals.selected}</b> të vlerësuara · <b id="okCount">0</b> mirë · <b id="wrongCount">0</b> gabim</p>
  <button class="copy" type="button" id="copyBtn">Kopjo vlerësimet</button>
</div>

<script>
  (function () {
    var STORAGE_KEY = "jara-bildvorschau-${label}";
    var cards = Array.prototype.slice.call(document.querySelectorAll(".card"));
    var marks = {};
    try { marks = JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}"); } catch (e) { marks = {}; }

    function persist() {
      try { localStorage.setItem(STORAGE_KEY, JSON.stringify(marks)); } catch (e) { /* private window */ }
    }

    function paint(card) {
      var mark = marks[card.dataset.code];
      if (mark) { card.dataset.mark = mark; } else { delete card.dataset.mark; }
      card.querySelectorAll(".verdict button").forEach(function (btn) {
        btn.setAttribute("aria-pressed", String(btn.dataset.mark === mark));
      });
    }

    function counts() {
      var values = Object.keys(marks).map(function (k) { return marks[k]; });
      document.getElementById("doneCount").textContent = String(values.length);
      document.getElementById("okCount").textContent =
        String(values.filter(function (v) { return v === "ok"; }).length);
      document.getElementById("wrongCount").textContent =
        String(values.filter(function (v) { return v === "wrong"; }).length);
    }

    var query = "";
    var status = "all";
    var brandFilter = [];

    function apply() {
      var visible = 0;
      cards.forEach(function (card) {
        var mark = marks[card.dataset.code];
        var okStatus =
          status === "all" ||
          (status === "found" && card.dataset.found === "true") ||
          (status === "missing" && card.dataset.found !== "true") ||
          (status === "open" && !mark);
        var okBrand = brandFilter.length === 0 || brandFilter.indexOf(card.dataset.brand) !== -1;
        var okQuery = query === "" || card.dataset.search.indexOf(query) !== -1;
        var show = okStatus && okBrand && okQuery;
        card.hidden = !show;
        if (show) visible++;
      });
      document.getElementById("empty").hidden = visible > 0;
    }

    document.getElementById("grid").addEventListener("click", function (event) {
      var button = event.target.closest(".verdict button");
      if (!button) return;
      var card = button.closest(".card");
      var code = card.dataset.code;
      marks[code] = marks[code] === button.dataset.mark ? undefined : button.dataset.mark;
      if (!marks[code]) delete marks[code];
      persist(); paint(card); counts(); apply();
    });

    document.getElementById("q").addEventListener("input", function (event) {
      query = event.target.value.trim().toLowerCase();
      apply();
    });

    document.getElementById("statusChips").addEventListener("click", function (event) {
      var chip = event.target.closest(".chip");
      if (!chip) return;
      status = chip.dataset.status;
      this.querySelectorAll(".chip").forEach(function (c) {
        c.setAttribute("aria-pressed", String(c === chip));
      });
      apply();
    });

    document.getElementById("brandChips").addEventListener("click", function (event) {
      var chip = event.target.closest(".chip");
      if (!chip) return;
      var brand = chip.dataset.brand;
      var at = brandFilter.indexOf(brand);
      if (at === -1) { brandFilter.push(brand); } else { brandFilter.splice(at, 1); }
      chip.setAttribute("aria-pressed", String(at === -1));
      apply();
    });

    document.getElementById("copyBtn").addEventListener("click", function () {
      var label = { ok: "mirë", unsure: "dyshim", wrong: "gabim" };
      var lines = cards
        .filter(function (card) { return marks[card.dataset.code]; })
        .map(function (card) {
          return [
            card.dataset.code,
            label[marks[card.dataset.code]],
            card.querySelector(".name").textContent.trim(),
          ].join("\\t");
        });
      var text = lines.length
        ? "Kodi\\tVlerësimi\\tProdukti\\n" + lines.join("\\n")
        : "Ende asgjë e vlerësuar.";
      var button = document.getElementById("copyBtn");
      navigator.clipboard.writeText(text).then(function () {
        button.textContent = "U kopjua ✓";
        setTimeout(function () { button.textContent = "Kopjo vlerësimet"; }, 1800);
      }, function () {
        button.textContent = "Kopjimi nuk lejohet";
        setTimeout(function () { button.textContent = "Kopjo vlerësimet"; }, 1800);
      });
    });

    cards.forEach(paint);
    counts();
    apply();
  })();
</script>
`;
}

function main() {
  const args = readArgs(process.argv.slice(2));
  if (!fs.existsSync(args.report)) {
    console.error(
      `Bericht fehlt: ${args.report}\nZuerst fetch-images.mjs laufen lassen.`,
    );
    process.exit(1);
  }
  const report = JSON.parse(fs.readFileSync(args.report, "utf8"));

  if (!args.skipThumbs) {
    const thumbs = spawnSync(
      "python3",
      [path.join(__dirname, "make-thumbs.py"), "--report", args.report],
      { encoding: "utf8" },
    );
    if (thumbs.status === 0) process.stdout.write(thumbs.stdout);
    else
      console.warn(
        "Hinweis: Thumbnails übersprungen (Pillow fehlt?) — die Seite wird größer.\n" +
          (thumbs.stderr || ""),
      );
  }

  const products = report.products;
  const brands = [...new Set(products.map((p) => p.brand).filter(Boolean))].sort();
  const cards = products.map((p, i) => card(p, i)).join("");
  const html = page(report, cards, brands);

  fs.mkdirSync(path.dirname(args.out), { recursive: true });
  fs.writeFileSync(args.out, html);
  const mb = (Buffer.byteLength(html) / 1024 / 1024).toFixed(1);
  console.log(`Vorschau geschrieben: ${args.out} (${mb} MB, ${products.length} Produkte)`);
  if (Number(mb) > 15) {
    console.warn("Achtung: über 15 MB — für eine Veröffentlichung als Seite zu groß.");
  }
}

main();
